/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./src/**/*.{vue,js,ts,jsx,tsx}"],
  theme: {
    extend: {
    fontFamily: {
        allura: ['"Allura"', 'cursive'],
        bangers: ['"Bangers"', 'cursive'],
        bebas: ['"Bebas Neue"', 'sans-serif'],
        bonheur: ['"Bonheur Royale"', 'cursive'],
        caveat: ['"Caveat"', 'cursive'],
        cinzel: ['"Cinzel"', 'serif'],
        cormorant: ['"Cormorant Garamond"', 'serif'],
        greatvibes: ['"Great Vibes"', 'cursive'],
        grenze: ['"Grenze Gotisch"', 'serif'],
        imfell: ['"IM Fell English SC"', 'serif'],
        indie: ['"Indie Flower"', 'cursive'],
        lato: ['"Lato"', 'sans-serif'],
        lobster: ['"Lobster"', 'cursive'],
        meow: ['"Meow Script"', 'cursive'],
        modern: ['"Modern Antiqua"', 'serif'],
        montserrat: ['"Montserrat"', 'sans-serif'],
        moolah: ['"Moo Lah Lah"', 'cursive'],
        nova: ['"Nova Square"', 'sans-serif'],
        roadrage: ['"Road Rage"', 'sans-serif'],
        robotoflex: ['"Roboto Flex"', 'sans-serif'],
        roboto: ['"Roboto"', 'sans-serif'],
        sacramento: ['"Sacramento"', 'cursive'],
        sawarabi: ['"Sawarabi Gothic"', 'sans-serif'],
        spectral: ['"Spectral SC"', 'serif'],
        vt323: ['"VT323"', 'monospace'],
      },
      colors: {
        primary: {
          50: "#ecfdf7",
          100: "#d1faec",
          200: "#a7f3da",
          300: "#6ee7c7",
          400: "#34d6ad",
          500: "#10bfa0", // PRIMARY MAIN
          600: "#0fa38a",
          700: "#0d8571",
          800: "#0b6a5a",
          900: "#095647",
        },
        secondary: {
          50: "#f0fdfa",
          100: "#ccfbf1",
          200: "#99f6e4",
          300: "#5eead4",
          400: "#2dd4bf",
          500: "#14b8a6", // SECONDARY MAIN
          600: "#0d9488",
          700: "#0f766e",
          800: "#115e59",
          900: "#134e4a",
        },
        neutral: {
          50: "#ffffff",
          100: "#f8fafc",
          200: "#e5e7eb",
          300: "#d1d5db",
          400: "#9ca3af",
          500: "#6b7280",
          600: "#4b5563",
          700: "#374151",
          800: "#1f2937",
          900: "#111827",
        },
        success: "#22c55e",
        warning: "#f59e0b",
        error: "#ef4444",
        info: "#3b82f6",
      },
      spacing: {
        18: "4.5rem",
        88: "22rem",
        100: "25rem",
        112: "28rem",
        128: "32rem",
      },
      borderRadius: {
        "2xl": "1.25rem",
        "3xl": "1.5rem",
        "4xl": "2rem",
      },
      boxShadow: {
        soft: "0 2px 8px rgba(0, 0, 0, 0.06)",
        card: "0 4px 16px rgba(0, 0, 0, 0.08)",
        float: "0 8px 24px rgba(0, 0, 0, 0.12)",
        glow: "0 0 40px rgba(34, 197, 94, 0.15)",
        "glow-lg": "0 0 60px rgba(34, 197, 94, 0.25)",
        "inner-glow": "inset 0 0 20px rgba(255, 255, 255, 0.1)",
      },
      animation: {
        float: "float 6s ease-in-out infinite",
        "float-delayed": "float 8s ease-in-out infinite 2s",
        "pulse-slow": "pulse 4s cubic-bezier(0.4, 0, 0.6, 1) infinite",
        shimmer: "shimmer 2s linear infinite",
        gradient: "gradient 8s ease infinite",
        "scale-in": "scaleIn 0.5s ease-out",
        "slide-up": "slideUp 0.6s ease-out",
        "slide-down": "slideDown 0.6s ease-out",
        "fade-in": "fadeIn 0.8s ease-out",
        "bounce-subtle": "bounceSubtle 2s ease-in-out infinite",
      },
      keyframes: {
        float: {
          "0%, 100%": { transform: "translateY(0px)" },
          "50%": { transform: "translateY(-20px)" },
        },
        shimmer: {
          "0%": { backgroundPosition: "-1000px 0" },
          "100%": { backgroundPosition: "1000px 0" },
        },
        gradient: {
          "0%, 100%": { backgroundPosition: "0% 50%" },
          "50%": { backgroundPosition: "100% 50%" },
        },
        scaleIn: {
          "0%": { opacity: "0", transform: "scale(0.9)" },
          "100%": { opacity: "1", transform: "scale(1)" },
        },
        slideUp: {
          "0%": { opacity: "0", transform: "translateY(30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        slideDown: {
          "0%": { opacity: "0", transform: "translateY(-30px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        fadeIn: {
          "0%": { opacity: "0" },
          "100%": { opacity: "1" },
        },
        bounceSubtle: {
          "0%, 100%": { transform: "translateY(0)" },
          "50%": { transform: "translateY(-10px)" },
        },
      },
    },
  },
  plugins: [],
};
